// pem2c - convert PEM-encoded X509 certificate and public key files to C header files
// Oliver Kuckertz, 2013-09-24, public domain

#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <stdio.h>
#include <string.h>

static
int process_x509_pem(BIO* in_bp, BIO* out_bp)
{
	X509* x;
	int   cert_count = 0;

	while (x = PEM_read_bio_X509(in_bp, NULL, NULL, NULL))
	{
		unsigned char* cert = NULL;
		int            cert_len;
		X509_NAME*     cert_subject_name;
		char           cert_cn[256];
		int            i;

		cert_len = i2d_X509(x, &cert);

		if (cert_len < 0)
		{
			fprintf(stderr, "i2d_X509 failed\n");
			return 1;
		}

		cert_subject_name = X509_get_subject_name(x);
		X509_NAME_get_text_by_NID(cert_subject_name, NID_commonName, cert_cn, sizeof(cert_cn));

		if (cert_count)
		{
			BIO_printf(out_bp, ",");
		}

		BIO_printf(out_bp, " \\\n    ");
		BIO_printf(out_bp, "/* CN = '%s', %d bytes */ \\\n    ", cert_cn, cert_len);

		for (i = 0; i < cert_len - 1; i++)
		{
			BIO_printf(out_bp, "0x%02X, ", cert[i]);

			if (i && (i + 1) % 16 == 0)
			{
				BIO_printf(out_bp, "\\\n    ");
			}
		}

		BIO_printf(out_bp, "0x%02X", cert[i]);

		cert_count++;

		OPENSSL_free(cert);
	}

	return (cert_count != 0) ? 0 : 1;
}

static
int process_pubkey_pem(BIO* in_bp, BIO* out_bp)
{
	EVP_PKEY* pkey;
	int       cert_count = 0;

	while (pkey = PEM_read_bio_PUBKEY(in_bp, NULL, NULL, NULL))
	{
		unsigned char* pkey_der = NULL;
		int            pkey_der_len;
		int            i;

		pkey_der_len = i2d_PUBKEY(pkey, &pkey_der);

		if (pkey_der_len < 0)
		{
			fprintf(stderr, "i2d_PUBKEY failed\n");
			return 1;
		}

		if (cert_count)
		{
			BIO_printf(out_bp, ",");
		}

		BIO_printf(out_bp, " \\\n    ");

		for (i = 0; i < pkey_der_len - 1; i++)
		{
			BIO_printf(out_bp, "0x%02X, ", pkey_der[i]);

			if (i && (i + 1) % 16 == 0)
			{
				BIO_printf(out_bp, "\\\n    ");
			}
		}

		BIO_printf(out_bp, "0x%02X", pkey_der[i]);

		cert_count++;

		OPENSSL_free(pkey_der);
	}

	return (cert_count != 0) ? 0 : 1;
}

static
void print_usage(const char* prog_name)
{
	fprintf(stderr, "usage: %s <x509|pubkey> <macro> [in.pem] [out.h]\n", prog_name);
}

int main(int argc, char* argv[])
{
	typedef int (*process_func)(BIO* in_bp, BIO* out_bp);

	BIO*         in_bp;
	BIO*         out_bp;
	char*        macro_name;
	char*        pem_type;
	process_func process;
	int          result;

	if (argc > 2)
	{
		pem_type   = argv[1];
		macro_name = argv[2];

		if (argc > 3)
		{
			in_bp = BIO_new_file(argv[3], "r");

			if (!in_bp)
			{
				fprintf(stderr, "failed to open input file\n");
				return 1;
			}
		}
		else
		{
			in_bp = BIO_new_fp(stdin, BIO_NOCLOSE);

			if (!in_bp)
			{
				fprintf(stderr, "BIO_new_fp failed\n");
				return 1;
			}
		}

		if (argc > 4)
		{
			out_bp = BIO_new_file(argv[4], "w");
			
			if (!out_bp)
			{
				fprintf(stderr, "failed to open output file\n");
				return 1;
			}
		}
		else
		{
			out_bp = BIO_new_fp(stdout, BIO_NOCLOSE);

			if (!out_bp)
			{
				fprintf(stderr, "BIO_new_fp failed\n");
				return 1;
			}
		}
	}
	else
	{
		print_usage(argv[0]);
		return 1;
	}

	if (strcmp(pem_type, "x509") == 0)
	{
		process = process_x509_pem;
	}
	else if (strcmp(pem_type, "pubkey") == 0)
	{
		process = process_pubkey_pem;
	}
	else
	{
		print_usage(argv[0]);
		return 1;
	}

	BIO_printf(out_bp, "// File generated by pem2c - do not edit\n\n");
	BIO_printf(out_bp, "#pragma once\n\n");
	BIO_printf(out_bp, "#define %s {", macro_name);
	
	result = process(in_bp, out_bp);

	BIO_printf(out_bp, " \\\n    }\n");

	BIO_free(in_bp);
	BIO_free(out_bp);

	return result;
}
